<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * LEADERBOARD — Materialized ranking table
 *
 * Generated by KpiLeaderboardJob after kpi_summaries are updated.
 * Pre-computed ranks mean O(1) reads for direktur dashboard.
 *
 * Two rank dimensions:
 *   rank_overall — across all employees
 *   rank_in_dept — within same department
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('leaderboard', function (Blueprint $table) {
            $table->id();

            $table->foreignId('user_id')
                ->constrained('users')
                ->cascadeOnDelete();

            $table->string('period_label', 20);
            $table->enum('period_type', ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'])
                ->default('monthly');

            // Mirrored from kpi_summaries for self-contained reads
            $table->decimal('total_score', 8, 4)->default(0);
            $table->decimal('achievement_rate', 8, 2)->default(0);
            $table->enum('score_label', ['excellent', 'good', 'average', 'bad'])->nullable();

            // Rank dimensions (NULL = user has no KPI data for this period)
            $table->unsignedSmallInteger('rank_overall')->nullable();
            $table->unsignedSmallInteger('rank_in_dept')->nullable();

            // Department denormalized for fast filtering without joins
            $table->foreignId('department_id')
                ->nullable()
                ->constrained('departments')
                ->nullOnDelete();

            $table->timestamp('generated_at')->nullable();
            $table->timestamps();

            // One row per user per period
            $table->unique(['user_id', 'period_label', 'period_type'], 'uniq_leader_user_period');

            // Direktur dashboard: top N overall in period
            $table->index(['period_label', 'rank_overall'], 'idx_leader_period_overall');

            // Department ranking view
            $table->index(['period_label', 'department_id', 'rank_in_dept'], 'idx_leader_period_dept');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('leaderboard');
    }
};
